- name: Init Swarm cluster
  hosts: manager
  gather_facts: False
  roles:
    - swarm-init

- name: Join Swarm cluster
  hosts: worker
  gather_facts: False
  vars:
      token: "{{ hostvars[groups['manager'][0]]['worker_token']['stdout'] }}"
      manager: "{{ hostvars[groups['manager'][0]]['inventory_hostname'] }}"
  roles:
    - swarm-join